### ISSUE TITLE
epoller wait failed in golang 1.14

### ISSUE THREAD

**Issue by liaoweiguo** [smallnest/1m-go-tcp-server#3]
in 5_multiple_client, line 99 the poll.waiter() failed with error: "interrupted system call"
connections, err := epoller.Wait()
		if err != nil {
			log.Printf("failed to epoll wait %v", err)
			continue
		}

with go version 1.13 OK

any suggestion?

**Comment by smallnest** [comment]
Go 1.14 release notes has said :

> A consequence of the implementation of preemption is that on Unix systems, including Linux and macOS systems, programs built with Go 1.14 will receive more signals than programs built with earlier releases. This means that programs that use packages like syscall or golang.org/x/sys/unix will see more slow system calls fail with EINTR errors. Those programs will have to handle those errors in some way, most likely looping to try the system call again. For more information about this see man 7 signal for Linux systems or similar documentation for other systems.

**Comment by liaoweiguo** [comment]
too much interrupt, seems stupid to retry again n again
