### ISSUE TITLE
Connection need to set nonblock?

### ISSUE THREAD

**Issue by M6ZeroG** [smallnest/1m-go-tcp-server#4]
https://github.com/smallnest/1m-go-tcp-server/blob/000556e59c21ac729f8f313b407127552721471f/2_epoll_server/epoll_linux.go#L36
Before we use `unix.EpollCtl()`  to add a connection to the event loop，Is it  necessary to use `unix.SetNonblock()` to set the connection to nonblock？

**Comment by smallnest** [comment]
Yes, I think we should invoke `unix.SetNonblock()`

**Comment by smallnest** [comment]
我认为Go在创建net.Conn时候，已经把它设置为Nonblock了，所以不需要我们再额外的设置了。
